# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ruby_deezer}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Aleksandr Lossenko"]
  s.date = %q{2011-03-05}
  s.description = %q{Search for artists, albums and tracks with Deezer API}
  s.email = %q{alossenko@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/ruby_deezer.rb",
    "lib/ruby_deezer/album.rb",
    "lib/ruby_deezer/artist.rb",
    "lib/ruby_deezer/track.rb",
    "pkg/ruby_deezer-0.1.0.gem",
    "ruby_deezer.gemspec",
    "test/fixtures/album.json",
    "test/fixtures/albums.json",
    "test/fixtures/artist.json",
    "test/fixtures/artists.json",
    "test/fixtures/track.json",
    "test/fixtures/tracks.json",
    "test/helper.rb",
    "test/unit/test_album.rb",
    "test/unit/test_artist.rb",
    "test/unit/test_track.rb"
  ]
  s.homepage = %q{http://github.com/egze/ruby_deezer}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{RubyDeezer is a ruby wrapper for the Deezer APIs}
  s.test_files = [
    "test/helper.rb",
    "test/unit/test_album.rb",
    "test/unit/test_artist.rb",
    "test/unit/test_track.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>, ["= 2.3.5"])
      s.add_runtime_dependency(%q<httparty>, ["~> 0.7.4"])
      s.add_runtime_dependency(%q<will_paginate>, ["= 2.3.15"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<fakeweb>, [">= 0"])
    else
      s.add_dependency(%q<activesupport>, ["= 2.3.5"])
      s.add_dependency(%q<httparty>, ["~> 0.7.4"])
      s.add_dependency(%q<will_paginate>, ["= 2.3.15"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<fakeweb>, [">= 0"])
    end
  else
    s.add_dependency(%q<activesupport>, ["= 2.3.5"])
    s.add_dependency(%q<httparty>, ["~> 0.7.4"])
    s.add_dependency(%q<will_paginate>, ["= 2.3.15"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<fakeweb>, [">= 0"])
  end
end

